# Generated by Django 2.0.2 on 2018-02-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('mailing_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('student_home_phone', models.CharField(max_length=100)),
                ('township_municipality', models.CharField(max_length=100)),
                ('parent_name_1', models.CharField(max_length=100)),
                ('parent_cell_1', models.CharField(max_length=100)),
                ('parent_work_1', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_1_email', models.EmailField(max_length=100)),
                ('parent_name_2', models.CharField(max_length=100)),
                ('parent_cell_2', models.CharField(max_length=100)),
                ('parent_work_2', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_2_email', models.EmailField(max_length=100)),
                ('parent_2_adress', models.CharField(max_length=100)),
                ('school_presently_attending', models.CharField(max_length=100)),
                ('guidance_counselor', models.CharField(max_length=100)),
                ('counselor_phone', models.CharField(max_length=100)),
                ('choice_1', models.CharField(max_length=100)),
                ('choice_2', models.CharField(max_length=100)),
                ('choice_3', models.CharField(max_length=100)),
            ],
        ),
    ]
